export const ADD_ITEMS_TO_CART= "ADD_ITEMS_TO_CART"
export const REMOVE_ITEMS_FROM_CART =" REMOVE_ITEMS_FROM_CART"
export const CLEAR_CART="CLEAR_CART"
export const SAVE_SHIPPING_INFO="SAVE_SHIPPING_INFO"

